### PR TITLE
Remove Freshman Project in Dashboard

### PR DESCRIPTION
**Pull request by jabbate19**
https://cshrit.slack.com/archives/CV0REE4JE/p1631659300194600

It doesn't exist, I got very confused when I saw it because it was never discussed. Apparently its been gone for a while, so why not just remove it from the dashboard?

### CODE REVIEW

**Review by mxmeinhold — APPROVED** [review]
LGTM! :ship: :it:

**Comment by galenguyer** [comment]
Please remove this reference as well: https://github.com/ComputerScienceHouse/conditional/blob/develop/conditional/util/member.py#L107

**Comment by jabbate19** [comment]
> Please remove this reference as well: https://github.com/ComputerScienceHouse/conditional/blob/develop/conditional/util/member.py#L107

Fixed @ https://github.com/jabbate19/conditional/commit/c21058935ad8929c2319d59bba7fb6496abebadf#diff-cf32113df94edd32e02734a11cb216107f2b9c1af05e23d3a5ae4407ccf6aac9

**Review by galenguyer — APPROVED** [review]
LGTM!

**Review by Mstrodl — APPROVED** [review]
LIGMA! :shipit:

**Pull request merged**
