### PR TITLE
Conditional v1.0.2

### PR DESCRIPTION
**Pull request by liam-middlebrook**
Includes several style changes and a critical bugfix for fid deletion.

### CODE REVIEW

**Comment by stevenmirabito** [comment]
👍  for everything but the rounded profile image on the dashboard. Please see #37.

**Comment by mbillow** [comment]
There is going to be an overhaul of that panel in the next version. I doesn't make sense (at least to me) to pull teeth and hold a release over it. We can work on the new version tonight.

**Comment by liam-middlebrook** [comment]
I've created #47 to push the hotfix through as soon as possible. Once we figure out the design changes that we'd like to finalize for this panel I can work on rebasing around the hotfix.

**Comment by liam-middlebrook** [comment]
@mbillow what's the plan for the panel changes? I'd like to get this PR merged before Sunday.

**Comment by liam-middlebrook** [comment]
I'd like to get this merged today. @stevenmirabito @mbillow thoughts?

**Pull request merged**
