### PR TITLE
Add GitHub Footer

### LINKED ISSUE #31: Add link to GitHub
It's super helpful for people to report bugs & realize that they can contribute if there's a link to the project page. Something simple like what Packet has at the footer would be perfect - it's not in your face, but always there for when you need it.

### PR DESCRIPTION
**Pull request by liam-middlebrook**
Fixes #31 

Currently untested, might look bad.

Special Shoutout to JDProfiles and TalPacket

### CODE REVIEW

**Comment by stevenmirabito** [comment]
👎 

I don't want to be that guy, but since I already am apparently this really isn't necessary and I do not want this added to the project.

**Comment by sman591** [comment]
@stevenmirabito Why is it unnecessary? We're a computing-driven organization - having an obvious location for a link only helps everyone contribute to the project, especially once the primary maintainers move on to other things

**Comment by csssuf** [comment]
Would changing the text to just "Conditional on GitHub" be a satisfactory compromise for everyone?

**Comment by liam-middlebrook** [comment]
Changed

**Comment by mbillow** [comment]
Added "Report an Issue" in user menu. I don't think a footer is necessary anymore.

**Comment by liam-middlebrook** [comment]
For the record I'd appreciate in the future if you could submit PRs for changes that aren't strictly critical bugfixes.

**Comment by gambogi** [comment]
@mbillow I don't see how "Report an Issue" solves the issue @sman591 raised. This isn't about creating issues, it's about making it easy for people to get involved to find the source. When someone is looking for this page, they aren't looking for a cutesy "Report an Issue" button.

**Comment by mbillow** [comment]
If people are looking to get involved they can find the repo. Look at members, packet (the non-Tal Packet-ified version), etc. If they want to contribute, I hope they know how to navigate to GitHub. There is no need to have a link on every page when most people are not going to click it.

No one has had a problem finding the repo to this point and we don't have a link now.

**Comment by sman591** [comment]
Finding a repo for a CSH project isn't at all standardized - this project just happened to be on the ComputerScienceHouse organization. Also, someone new to CSH (or open source in general) probably *wouldn't* know where to start, nonetheless navigate GitHub.

Examples: the public site. Up until recently, ComputerScienceHouse's repo was a fork of someone else's work. CSH Drink, both iOS and Android, are member-owned repos - the same goes for countless other projects.

The only way I easily found this was on the Discourse announcement post - something someone 4 years from now wouldn't even know exists. Googling for the repo isn't ideal - if the namespace clashes with existing GitHub projects, or anything else on the internet, it could be hard to find.

Removing the friction of someone trying to find the repo only helps people get involved. We shouldn't assume people know how to navigate GItHub.

**Comment by mbillow** [comment]
@sman591 If there is a frictionless way that isn't adding a footer, I have no issue with a link. I just don't think we need something in the user's face on every page.

**Pull request closed without merging**
