### PR TITLE
Added theme Color

### PR DESCRIPTION
**Pull request by devinmatte**
I know this is a tiny tiny change, but I really like seeing our house services with the themed header/tab

### CODE REVIEW

**Comment by mbillow** [comment]
Looks good to me. I would love to see this also incorporated: https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

Lets not just be bias towards Android users! :P 

You can use the icon from members, if you want.

**Comment by devinmatte** [comment]
I was going to add a manifest.json, but I could not figure out where to place it since /static doesn't exist exactly and I'm not sure where I would put it.
If someone helps out with that I'll look into implementing this as well

**Comment by mbillow** [comment]
Everything [here](https://github.com/ComputerScienceHouse/conditional/tree/develop/frontend/images) gets compressed and then served from `/static` via a versioned file name. @stevenmirabito would be able to talk more about that.

**Comment by liam-middlebrook** [comment]
What's up with the new anonymous merge commit? Was it intentional?

**Comment by devinmatte** [comment]
There was a merge conflict since I opened this PR.

**Comment by liam-middlebrook** [comment]
Oh okay. Then please rebase your changes on top of develop in order to avoid an anonymous merge commit.

**Comment by devinmatte** [comment]
Fixed my Commit and added Pinned tab support for @mbillow, also threw in Windows Pinned support while I was at it

**Pull request closed without merging**
