### PR TITLE
Add handling failure case for introductory evals

### LINKED ISSUE #97: Button to clear conditional information
If someone fails after their account is migrated, if they ever apply again their old data still exists in the database.

### PR DESCRIPTION
**Pull request by liam-middlebrook**
Automatically remove all data about a user who fails their introductory
evaluation.

Fixes #97

### CODE REVIEW

**Comment by mbillow** [comment]
If we just delete everything, their listing on the Intro Evals page will say they didn't have any committee meetings, seminars, etc.

Also, we need to grab Intro Eval questions too.

**Comment by liam-middlebrook** [comment]
Okay, so I just need to also delete their entry in FreshmanEvalData also?

**Comment by mbillow** [comment]
I'm not sure that is the right route... Then we would only show people who passed or are pending on that page, which isn't a correct representation of what happened throughout the year. I think this is a good use of the "active" field in our schema. 

Another problem is that we relate committee meetings to a UID not a SpringEvals object. So if Joe tries three times he has three "failed" IntroEvals objects but all of his committee meetings will show up for all of his entries...

**Comment by mbillow** [comment]
The easy way out is to just delete everything, but the easy route isn't always the best one.

**Comment by liam-middlebrook** [comment]
I originally had a fix that didn't delete records (as you pointed out, isn't exactly the ideal solution), which was labeled as PR #100.

Here's a link to the context around me updating that PR on 1/9/17 and then deciding to go with the deletion instead on 1/20/17: https://cshrit.slack.com/archives/C246XBLTV/p1483988377001186

**Pull request closed without merging**
