### PR TITLE
Conditional v1.3

### PR DESCRIPTION
**Pull request by mbillow**
## Improvements:
- [X] Migrate to CSH LDAP ORM
- [X] Re-implement Housing Queue
- [X] Alter submitted Committee Meetings
- [X] In-Line Housing Update Functionality

## Bug Fixes / Misc:
- [X] Better Model Documentation
- [X] Revision Footer Added
- [X] Only Show Relevant Housing Info on Dashboard
- [X] `BUG` Correct Dashboard Member Statistics
- [X] `BUG` Upperclassmen No Longer Disappear when Evaluated
- [X] `BUG` LDAP Cache Invalidation

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Are we planning on integrating #100, last time we discussed this on Slack we circled from the standpoint of deleting the data to keeping it with the model I currently have setup.

**Comment by mbillow** [comment]
I would like to, but I don't remember the conversation ever turning in favor of keeping the data. Last time I checked @stevenmirabito and I both were of the stand-point that irrelevant data should just be removed.

**Comment by stevenmirabito** [comment]
Updated the v1.3 milestone and the parent comment to reflect that Docker and OIDC will be pushed to v1.4.

**Comment by stevenmirabito** [comment]
🚢

**Pull request merged**
