### PR TITLE
Add standard icon spacing for all icons

### PR DESCRIPTION
**Pull request by sman591**
* Sets a standard distance for all icon spacing
* Uses em so that it scales proportionally to font size

I use this in all my projects as I think icons look a ton better when they're not up right against the text. Adding a space only does so much, and spaces can't stack to increase the distance.

I couldn't get a local environment working so I couldn't fully test this locally, but applying my changes in the web inspector looks like this:

Before:
screenshot 2016-09-07 21 52 25

After:
screenshot 2016-09-07 21 59 05

### CODE REVIEW

**Comment by mbillow** [comment]
Hot. 🔥

**Comment by stevenmirabito** [comment]
@sman591 Looks great, although I think this would be more appropriate as an addition to [csh-material-bootstrap](https://github.com/ComputerScienceHouse/csh-material-bootstrap). I'm trying to keep all style changes in the library so everything looks consistent across apps. If you could make this change over there, preferably as default behavior for glyphicons in navbars, that would be very much appreciated.

**Comment by sman591** [comment]
@stevenmirabito Sure thing. I'll update this PR once I've added it there.

**Comment by stevenmirabito** [comment]
Closing as this has been added to [csh-material-bootstrap](https://github.com/ComputerScienceHouse/csh-material-bootstrap/pull/1) and will be added to this project pending the release of v1.0.1 of that library.

**Pull request closed without merging**
