### PR TITLE
Retry eval process

### LINKED ISSUE #97: Button to clear conditional information
If someone fails after their account is migrated, if they ever apply again their old data still exists in the database.

### PR DESCRIPTION
**Pull request by liam-middlebrook**
This should fix #97

### CODE REVIEW

**Comment by hale6666** [comment]
What's the status on this?  Now that my account's reactivated, I seem to have two accounts on Conditional.  One (my original one) shows the meetings I went to during last evals (_and_ one during my second packet), but shows as inactive.  The other shows as an internal account with no attendance.

**Comment by mbillow** [comment]
You changed the model but didn't create a migration. I am not sure if setting active to false is what we want to do here... I think it should just delete the record.

**Comment by mbillow** [comment]
@liam-middlebrook Having spent more time thinking about it, it only makes sense to delete the data. It is useless and we only care about freshmen evals for those who pass. Personally, I would like to see the data purged when the member fails.

**Comment by liam-middlebrook** [comment]
In that case would freshman_eval_result only be able to support statuses of Pending or Passed? Because in the system you described people who failed would simply disappear from the database, not even with a record of failure

**Comment by liam-middlebrook** [comment]
After some discussion on Slack I decided to fix this outstanding pull request.

**Pull request closed without merging**
