### PR TITLE
Bring master up to date with dev

### PR DESCRIPTION
**Pull request by Mstrodl**
Seems to be mostly little housekeeping stuff, but I didn't look that hard :P

### CODE REVIEW

**Review by mxmeinhold — APPROVED** [review]
Please make sure this works in dev

**Comment by Mstrodl** [comment]
Shit's fucked

**Comment by mxmeinhold** [comment]
> Shit's fucked

Does this mean that I should or should not approve this...?

**Comment by galenguyer** [comment]
Mary is just dumb, shit isn't fucked

**Review by mxmeinhold — APPROVED** [review]

**Review by galenguyer — APPROVED** [review]

**Pull request merged**
