### PR TITLE
Conditional 1.1.0

### PR DESCRIPTION
**Pull request by liam-middlebrook**
Add Major Project Deletion

Add Conditional Form

Fix OnFloorStatus Assigned

Fix LDAP Field Removal

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Not sure if we want to wait for the oidc branch to be merged into develop before v1.1.0

**Comment by mbillow** [comment]
Depends on the status of @stevenmirabito and that branch. I would like to see OIDC to be in the hands of the RTPs before we continue the roll out and because of that, I think it makes sense to not include it in this release.

**Comment by liam-middlebrook** [comment]
@mbillow that seems reasonable to me. Just wasn't sure if we wanted to bunch these both into the minor 1.1.0 release.

**Comment by liam-middlebrook** [comment]
Before we merge this we should actually test that https://github.com/ComputerScienceHouse/conditional/pull/75/commits/0a1b79d538c78b8afdf0e19e4a8ae53b1ca831d5 works.

**Comment by mbillow** [comment]
Ship it! :ship:

**Pull request merged**
